### ISSUE TITLE
How to assign SSH keys to Kubernetes worker instances?

### ISSUE THREAD

**Issue by zedtux** [ovh/terraform-provider-ovh#388]
Hi there,

I would like to create SSH keys using `ovh_me_ssh_key` and assign them to the created instances by `ovh_cloud_project_kube` and `ovh_cloud_project_kube_nodepool` but I can't figure it out.

Can you please guide me on this task ?

### Affected Resource(s)
- ovh_me_ssh_key
- ovh_cloud_project_kube
- ovh_cloud_project_kube_nodepool

### Expected Behavior
Allowing to attach SSH keys to Kubernetes worker nodes.

### Actual Behavior
The Kubernetes worker nodes have no SSH keys assigned.

**Comment by yomovh** [comment]
Thanks for your issue, unfortunately it is not possible to ssh into the worker node since this is a managed service. So since the managed kubernetes service do not provide that feature, it is not possible to automate it in Terraform.

This limitation is described in this page :  https://docs.ovh.com/fr/kubernetes/known-limits/

**Comment by zedtux** [comment]
Thank you for your reply.
