### ISSUE TITLE
[BUG] Unexpected behavior when updating kubernetes nodepool

### ISSUE THREAD

**Issue by Char31** [ovh/terraform-provider-ovh#419]
### Describe the bug

Whenever you update the node pool profile, the original pool is deleted without waiting for confirmation of the availability of the new node pool

### Terraform Version
v1.4.6

### OVH Terraform Provider Version

v0.30

### Affected Resource(s)

Please list the resources as a list, for example:
- ovh_cloud_project_kube_nodepool

### Terraform Configuration Files

```hcl
resource "ovh_cloud_project_kube_nodepool" "node_pool" {
  service_name  = var.service_name
  kube_id       = ovh_cloud_project_kube.my_kube_cluster.id
  name          = "my-pool"
  flavor_name   = "i1-45" // changed from b2-30
  autoscale     = true
  desired_nodes = 3
  max_nodes     = 6
  min_nodes     = 3

  timeouts {
    create = "1h"
    update = "45m"
    delete = "20m"
  }
}
```

### Expected Behavior

update profile of the nodes by adding new nodes with the new profile , then evecting pods from the old nodes , followed up by deleting the old nodes

### Actual Behavior

The original nodepool was deleted, then I had to wait for more then 1h30 for the new nodepool to be available, another weird behavior is that if you misspelled the flavor name terraform plan passes with no issues, however when you deploy terraforme will just delete your original nodepool and sends you this error

```
...
Terraform has been successfully initialized!
Acquiring state lock. This may take a few moments...
ovh_cloud_project_kube_nodepool.node_pool: Destroying... [id=a2116c71-e3a7-4614-a60e-dd4a10ee3d9f]
ovh_cloud_project_kube_nodepool.node_pool: Still destroying... [id=a2116c71-e3a7-4614-a60e-dd4a10ee3d9f, 10s elapsed]
ovh_cloud_project_kube_nodepool.node_pool: Still destroying... [id=a2116c71-e3a7-4614-a60e-dd4a10ee3d9f, 20s elapsed]
ovh_cloud_project_kube_nodepool.node_pool: Still destroying... [id=a2116c71-e3a7-4614-a60e-dd4a10ee3d9f, 30s elapsed]
ovh_cloud_project_kube_nodepool.node_pool: Still destroying... [id=a2116c71-e3a7-4614-a60e-dd4a10ee3d9f, 40s elapsed]
ovh_cloud_project_kube_nodepool.node_pool: Still destroying... [id=a2116c71-e3a7-4614-a60e-dd4a10ee3d9f, 50s elapsed]
ovh_cloud_project_kube_nodepool.node_pool: Still destroying... [id=a2116c71-e3a7-4614-a60e-dd4a10ee3d9f, 1m0s elapsed]
ovh_cloud_project_kube_nodepool.node_pool: Still destroying... [id=a2116c71-e3a7-4614-a60e-dd4a10ee3d9f, 1m10s elapsed]
ovh_cloud_project_kube_nodepool.node_pool: Still destroying... [id=a2116c71-e3a7-4614-a60e-dd4a10ee3d9f, 1m20s elapsed]
ovh_cloud_project_kube_nodepool.node_pool: Still destroying... [id=a2116c71-e3a7-4614-a60e-dd4a10ee3d9f, 1m30s elapsed]
ovh_cloud_project_kube_nodepool.node_pool: Still destroying... [id=a2116c71-e3a7-4614-a60e-dd4a10ee3d9f, 1m40s elapsed]
ovh_cloud_project_kube_nodepool.node_pool: Still destroying... [id=a2116c71-e3a7-4614-a60e-dd4a10ee3d9f, 1m50s elapsed]
ovh_cloud_project_kube_nodepool.node_pool: Destruction complete after 1m59s
ovh_cloud_project_kube_nodepool.node_pool: Creating...
╷
│ Error: calling Post /cloud/project/e2f937e0eba64d5f8bdfa3[62](https://gitlab.unowhy.dev/dev/gitops_heaven/infrastructure/-/jobs/351590#L62)5529102d/kube/2245e592-12fa-47b2-8ee7-dd43[64](https://gitlab.unowhy.dev/dev/gitops_heaven/infrastructure/-/jobs/351590#L64)c7b148/nodepool with params my-pool(I1-45): 3/3/6:
│ 	 HTTP Error 404: Client::NotFound: "[NotFoundError] 404: Flavor I1-45 not found (request ID: 79c806b8-6c3f-485d-b809-c02b4dd3613c)" (X-OVH-Query-Id: EU.ext-2.645a2453.49230.[73](https://gitlab.unowhy.dev/dev/gitops_heaven/infrastructure/-/jobs/351590#L73)cc4cab-7ba7-402b-aa81-146d24ec9[74](https://gitlab.unowhy.dev/dev/gitops_heaven/infrastructure/-/jobs/351590#L74)9)
│ 
│   with ovh_cloud_project_kube_nodepool.node_pool,
│   on main.tf line 29, in resource "ovh_cloud_project_kube_nodepool" "node_pool":
│   29: resource "ovh_cloud_project_kube_nodepool" "node_pool" {
│ 
╵

``` 

### Steps to Reproduce

1- create your culster with an initial nodepool 
2- change the flavor_name 
3- terraform plan and apply commands

**Comment by matprig** [comment]
Hello,

flavor_name is a required field and when changing this field re-creation of the resource is necessary, by the way the resource will be destroyed and then the new one will be created which is terraform expected behavior and this is written by terraform when performing the plan, asking you for confirmation.

As written in the documentation the flavor is not an updatable field https://help.ovhcloud.com/csm/en-public-cloud-kubernetes-node-pools-crd?id=kb_article_view&sysparm_article=KB0049916 "flavor, monthlyBilled and antiAffinity are not editable."

For the flavor not found, you shall use a terraform data to be sure to use a flavor that exists https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/data-sources/compute_flavor_v2 and refer to it

note that not all flavor are available for kubernetes, this can be obtain with this endpoint https://eu.api.ovh.com/console/#/cloud/project/{serviceName}/capabilities/kube/flavors~GET

maybe a dedicated terraform data kubernetes flavor calling this endpoint should be added to the provider

best

**Comment by Char31** [comment]
My question then would be if the "flavor, monthlyBilled and antiAffinity are not editable." Shouldn't the terraform plan respond with something like this : 

- error pool already existe 
- error  can't create pool with the same name ...

i mean we are in a multicloud environnement we expecte the same behivior from all our update processes , the reason behind terraforme state is to prevent accidental resource deletion don't you think?

also for the second issue why not force the use of the  "openstack_compute_flavor_v2" , insted of allowing the use of flavor_name?

here to help :) 
Kind regards

**Comment by matprig** [comment]
hello,

Terraform when printing the plan is explicit for example i changed the flavor_name and it prints:

...
  # ovh_cloud_project_kube_nodepool.xxx must be replaced
...
      ~ flavor_name      = "b2-7" -> "b2-15" # forces replacement
...
Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 


best,

**Comment by yomovh** [comment]
@Char31 : about the flavor issue, it is not possible to have a fixed list of flavors name in kube attribute definition (since they are dynamic) and AFAIK dependency between providers in terms of input types are not possible. 

So to avoid having an error after the nodes have been destroyed,  I would use the [flavor data source](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/data-sources/compute_flavor_v2) to be sure that the spelling is correct and then use the [name](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/data-sources/compute_flavor_v2#name) attribute in your kube cluster definition.
