### ISSUE TITLE
[FEATURE] Use existing floating IP on gateway

### ISSUE THREAD

**Issue by 131** [ovh/terraform-provider-ovh#675]
### Description

Creating a gateway will pick a new IP from the external network pool.
I want to use/choose one of my available floating IP (so i can keep my IP / if I destroy / update my gateway)

### Affected Resource(s) and/or Data Source(s)

*ovh_cloud_project_gateway

### Potential Terraform Configuration

```

resource "ovh_cloud_project_gateway" "gateway" {
  service_name = ovh_cloud_project_network_private.mypriv.service_name
  name          = "my-gateway"
  model         = "s"
  region        = ovh_cloud_project_network_private_subnet.myprivsub.region
  network_id    = tolist(ovh_cloud_project_network_private.mypriv.regions_attributes[*].openstackid)[0]
  subnet_id     = ovh_cloud_project_network_private_subnet.myprivsub.id
  floating_ip   = X.Y.Z.A
}
```

[Using a floating IP in front of the gateway is explicitly stated in OVH documentation](https://help.ovhcloud.com/csm/en-public-cloud-network-concepts?id=kb_article_view&sysparm_article=KB0050134)

**Comment by yomovh** [comment]
Hello,

Thanks for your issue. 

It is currently not possible to assign a floating IP to a gateway (see this [question](https://help.ovhcloud.com/csm/en-ie-public-cloud-network-faq?id=kb_article_view&sysparm_article=KB0050251#will-gateway-be-provided-with-a-public-ip-and-port) in the public cloud network FAQ page. This [issue](https://github.com/ovh/public-cloud-roadmap/issues/448) is the corresponding roadmap item. Please add a thumb up 👍  and a comment to show your interest 🙏 

I would be interested to know which part of the documentation page you mentioned  made you think this was possible. So that I can update it to clarify it. Can you quote that part ?

**Comment by 131** [comment]
THank your for th related issue / i've upvoted the request.
Regarding the documentation, you'll see on  those diagrams
* https://help.ovhcloud.com/public_cloud-public_cloud_network_services-concepts-01-public-cloud-networking-concepts-images-netcon3.png
* https://help.ovhcloud.com/public_cloud-public_cloud_network_services-concepts-01-public-cloud-networking-concepts-images-netcon4.png

Floating IPs in front of a gateway, because, "of course" this i how it's intended to be used. There come the unfortunate deception.

**Comment by yomovh** [comment]
I have created a [doc issue](https://github.com/ovh/docs/issues/6592) based on your feedback, I will hence close this issue, let's do the follow up on the other one.
