### ISSUE TITLE
[FEATURE] [Logs Data Platform] Get the write token of a logs data stream 

### ISSUE THREAD

**Issue by pgillet** [ovh/terraform-provider-ovh#686]
### Description

It is not possible to retrieve the write token of a logs data stream within Terraform, while the HTTP endpoint `GET /dbaas/logs/{serviceName}/output/graylog/stream/{streamId}/rule/{ruleId}` exists in the OVHcloud HTTP API. 

### Affected Resource(s) and/or Data Source(s)

* ovh_dbaas_logs_graylog_output_stream

### Potential Terraform Configuration

If would be convenient to return a `write_token` attribute in the resource (and data source) `ovh_dbaas_logs_graylog_output_stream` or to add a new resource/data source just to get the token associated to a data stream.

**Comment by 131** [comment]
For now, using the API to retrieve this is a pain, when everything else can be properly handled by the terraform provider

**Comment by amstuta** [comment]
Hello @pgillet, thanks for your issue.
I guess the better solution would be to add a field in resource/datasource `ovh_dbaas_logs_graylog_output_stream` like you said, with the value being empty if you are not the owner of the stream (since in that case you don't have access to the write token).
We will work on this shortly.

**Comment by pgillet** [comment]
That was fast!

For my understanding, does it mean that we have to provide our own token when creating the data stream?

**Comment by amstuta** [comment]
No, the write token is only computed, you cannot import it manually ;)
