### ISSUE TITLE
ovh_cloud_network_private_subnet resource has no dns_nameservers option

### ISSUE THREAD

**Issue by gregoiremahe** [ovh/terraform-provider-ovh#90]
Hi,

We need to configure dns nameservers for private subnet in OpenStack to avoid a wrong DNS configuration after the deployment.

This option on openstack subnet is not available on ovh resource

**Comment by theOSCARP** [comment]
Up.
In 2023, the private network is delivery with no DNS Server. It's complicated to resolve OVH services (DBaas, etc...)

**Comment by yomovh** [comment]
Hello,

For some resources like network, we advice to use the openstack provider because they are more complete. See that [page](https://help.ovhcloud.com/csm/en-gb-terraform-at-ovhcloud?id=kb_article_view&sysparm_article=KB0054612)

The following github project provides simple example including openstack user creation from ovh token : https://github.com/yomovh/tf-at-ovhcloud/tree/main/private_network
